name: Deploy fetch alerts cloud functions to google
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - 'develop'
      - 'master'
    paths:
      - 'cloud-functions/fetch-alerts/**'
  workflow_dispatch:
jobs:
  run:
    name: Deploy fetch alerts cloud function
    runs-on: ubuntu-24.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
    - id: auth
      name: Authenticate in google cloud services
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'
    - id: 'deploy'
      name: GC Functions deployment
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      timeout-minutes: 10
      with:
        name: 'fetch-alerts'
        runtime: 'nodejs22'
        entry_point: 'fetchAlerts'
        memory_mb: '128'
        region: 'us-central1'
        source_dir: 'cloud-functions/fetch-alerts'
    # Example of using the output
    - id: 'test'
      name: GC Functions testing deployment
      run: 'curl "${{ steps.deploy.outputs.url }}"'
